# Generated by Django 3.2.8 on 2022-01-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
